### PR TITLE
Support for KV Storage

### PR DESCRIPTION
**Pull request by ch99q**
See more at https://miniflare.dev/storage/kv 

Added arguments
```
--k, --kv <namespace>      KV namespace to bind
     --kv-persist [path]   Persist KV data (to optional path)
```

Add bindings to KV in typescript
```ts
declare global {
  var MyKVNamespace: KVNamespace;
}
```

Remeber to reference the bindings correctly in wrangler.toml according to [developers.cloudflare.com/workers](https://developers.cloudflare.com/workers/runtime-apis/kv/?_gl=1*1khfq29*_ga*MTAxMzcxOTIwNy4xNjQ5MTQyMTM0*_gid*Njk4NTE2MTAuMTY0OTE0MjEzNA..#kv-bindings)

### CODE REVIEW

**Comment by Aslemammad** [comment]
@ch99q Hey, Thanks for the PR. Could you add a test case for it?

**Comment by ch99q** [comment]
> @ch99q Hey, Thanks for the PR. Could you add a test case for it? 

Not sure how you would test it when it's only a thing happening at their production site. To implement it locally would be adding an environment variable in .env to support this.

(btw the .env is not working, going to make a pull request in a sec to fix this)

**Comment by Aslemammad** [comment]
@ch99q Could you also make tests pass for this? and please pull from main so you'd be updated!

**Comment by ch99q** [comment]
> so

Should work now ☺️

**Comment by Aslemammad** [comment]
@ch99q Thank you so much!

**Pull request merged**
