### PR TITLE
fix: modules option

### PR DESCRIPTION
**Pull request by Aslemammad**

### CODE REVIEW

**Comment by carlreid** [comment]
Hey, is there a possibility you could push this fix? Don't think I can see it in `4.0.0`. Assume it will fix the issue I see:

```
MiniflareCoreError [ERR_MODULE_DYNAMIC_SPEC]: Unable to resolve "<script:0>" dependency: dynamic module specifiers are unsupported.
You must manually define your modules when constructing Miniflare:
  new Miniflare({
    modules: [
      { type: "ESModule", path: "<script:0>" }
    ]
  })
```

**Comment by Aslemammad** [comment]
done @carlreid 
image

**Comment by carlreid** [comment]
Thanks @Aslemammad! Unfortunetly, I still get the same issue above. Not sure if I should open an issue for it specifically, or maybe it's just be being dumb.

I get it with using your example `vite-plugin-ssr` with some changes, using `index.ts` (note TypeScript) and when trying to use the `import { renderPage } from 'vite-plugin-ssr'`.

I also seem to run into some other trouble where `esbuild.context` is not defined, when in my main project that uses Terborepo. Though I didn't manage to replicate that when using a new Turborepo example, with your `vite-plugin-ssr` example project.

Possibly could be related to newer versions, lease I am running on latest versions:
image

**Comment by Aslemammad** [comment]
Sure, feel free to create a new issue, so i check it.

**Pull request merged**
